### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by rosstex** [ThomasOrlita/remove-people-also-search-for-box#1]
Just wanted to say thank you for making this. I'm glad I am not alone in hating Google for that

**Comment by ThomasOrlita** [comment]
Thanks! It's great to see that this makes Google search results a bit more usable.

[![image](https://user-images.githubusercontent.com/17808846/149654014-b53926c4-9d2b-4b76-8d1b-ec3b40707014.png)
](https://twitter.com/ShitUserStory/status/1417764257626734593/)
